### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ijlalansari1122**
assets and posts folder moved

### CODE REVIEW

**Comment by ijlalansari1122** [comment]
Posts folder was updated

**Review by oba2311 — COMMENTED** [review]
We don't need th forty file please omit thanks

**Comment by ijlalansari1122** [comment]
That is due to high number of images and posts both combine to make this number

**Comment by ijlalansari1122** [comment]
Checking stuff

**Comment by ijlalansari1122** [comment]
hello

**Review by oba2311 — APPROVED** [review]

**Pull request merged**
